### PR TITLE
Use homebrew instead of MacPorts

### PR DESCRIPTION
**Pull request by genevera**
considers homebrew as per #3

### CODE REVIEW

**Comment by essandess** [comment]
Thanks for starting this PR.

I suggest the following approach to incorporate Homebrew. I’ll need to defer to those who run Homebrew to check functionality.

* Make the install script work for either Macports or Homebrew.
* In the [readme-and-install.sh](../readme-and-install.sh) script, set up a test for Macports versus Homebrew that will set appropriate environment variables for the install, e.g.
```
LOCAL_INSTALL=/opt/local  # or /usr/local
```
* Use `sed` Within the install script to edit the existing files rather than replacing files in the repo, e.g. this [edit](https://github.com/essandess/macOS-Fortress/pull/6/commits/1d457c77ded4701f2e81c5c6ffa99314128a5a02).
* Avoid writing over files that limit the functionality to just brew.
* This PR does not yet include all the edits necessary to get working `squid` or `privoxy` proxies with brew. E.g. the configuration file (squid.conf)[../squid.conf] has explicit dependencies on `/opt/local`.
* Confirm that everything works with a Homebrew-based install prior to committing to a merge.

**Comment by genevera** [comment]
I could have sworn I seded everything in the repo!

**Comment by essandess** [comment]
Here’s a `bash` command line check for Macports versus Homebrew:

```
bash -ic 'if [ -x /opt/local/bin/port ] && ! [ -x /usr/local/bin/brew ]; then echo "Macports"; elif [ -x /usr/local/bin/brew ] && ! [ -x /opt/local/bin/port ]; then echo "Homebrew"; fi'
```

I suggest adding this logic to the install script and using it to set an appropriate variable or two, then using the basic logic that’s already in the install script, modified by the addition of a few `sed` commands to change the default Macports file configuration settings to Homebrew settings.

Sanity check a running version and make sure it all works. Browsing to http://p.p is the simplest check.

Grep everything for `/opt/local` to find the Macports dependencies. Note that this includes the (important) [disable.sh](../disable.sh) as well.

**Comment by genevera** [comment]
@essandess do you have a macos VM image that you use to test this out?  i'm happy to use any host software but am uneasy about testing directly on my personal machine

**Comment by essandess** [comment]
I do not have a MacOS VM.

FWIW, I personally run the install script on all new boxes I configure/reconfigure, and it’s been bulletproof for me.

All the stuff that get’s installed is simply ports like `squid` etc. configured as per this repo, along with a few launch daemon plists. It’s very easy to undo everything. It’s also possible to just run the commands one-at-a-time from the command line to see what everything is doing.

**Comment by essandess** [comment]
The repo and this PR have diverged since I've added clamav support.

I'm in the final stages of migrating defunct macOS Server.app services into MacPorts ([DNS](https://github.com/macports/macports-ports/blob/master/net/dns-server/Portfile), [VPN](https://github.com/macports/macports-ports/blob/master/net/macos-vpn-server/Portfile), …), and ultimately see this repo just being a MacPorts install.

Because the main difference between MacPorts and Brew is often just a different `PREFIX` location (as reflected in this PR), it would be good to try to sync the MacPorts and Brew approaches, and I'll keep this PR in mind when I get around to a MacPorts submission.

That said, I have reservations about brew's support of startup launchd services and the system-wide, integrated, destroot'ed services required here.

Is brew able to perform system level installs of the sort handed by e.g., the MacPorts [clamav-server](https://github.com/macports/macports-ports/blob/master/sysutils/clamav-server/Portfile)?

Ultimately, this repo will be installed and controlled with a bunch of MacPort-generated plist system-level launch daemons. How can this be done in parallel within brew?

**Comment by smkolins** [comment]
I would also suggest the firewall configuration module…

> On Jul 14, 2019, at 9:45 AM, Steve Smith <notifications@github.com> wrote:
> 
> I'm in the final stages of migrating defunct macOS Server.app services into MacPorts (DNS <https://github.com/macports/macports-ports/blob/master/net/dns-server/Portfile>, VPN <https://github.com/macports/macports-ports/blob/master/net/macos-vpn-server/Portfile>, …), and ultimately see this report just being a MacPorts install.

=    -   -  - - -  -   -    =
Steven Kolins
mailto:smkolins@mac.com
http://smk99.blogspot.com/
Possess a pure, kindly and radiant heart!

**Comment by essandess** [comment]
@smkolins That's a good idea.  I plan to modularize as much as possible.

**Comment by essandess** [comment]
I’ve looked more into Homebrew and see that its security model is incompatible with this repo. I cannot personally recommend Homebrew’s approach, especially for a repo that does its best to keep things locked down.

All of the tools in this repo should be installed and controlled securely at the system level with `sudo`. Homebrew avoids `sudo` by taking over permissions in `/usr/local`. This won’t work here.

For more details on the issues that can arise with Homebrew’s approach, I agree with much of the criticism in this post: https://saagarjha.com/blog/2019/04/26/thoughts-on-macos-package-managers/.

**Pull request closed without merging**
